FROM rocker/r-ver:4.3.3


# 1) Install renv so we can restore packages from renv.lock
RUN install2.r --error --skipinstalled renv

# 2) Create a working directory and copy your entire project there
WORKDIR /app
COPY . /app

# 3) Restore packages according to renv.lock
RUN R -e 'renv::restore()'

# 4) Copy RStudio interface preferences (if needed)
COPY rstudio-prefs.json /home/rstudio/.config/rstudio/rstudio-prefs.json
